### ISSUE TITLE
how to do inference using speaker recognition checkpoint on raw audio file.

### ISSUE THREAD

**Issue by alam-botify** [joaoantoniocn/AM-MobileNet1D#3]
I am trying to reproduce the results on timit dataset.

I am having some doubt related to inference:

1. I have not seen any documentation for inferring a pre-trained model/checkpoint on sample audio data.
So I want to do inference on the raw mono audio file for the speaker recognition, can you suggest the command or step for inferring an output?

2. Can you suggest a link of your pre-trained model on timit dataset to compare it with the reproduced one?

If I want to train a model on my own dataset then how can I generate data_lists (.npy) files?

**Comment by joaoantoniocn** [comment]
Hi,
1.
If you have a pre-trained model you can set it on the cfg file, there on the data section (first section) you have to set the path for your pre-trained model on the 'pt_file' parameter;

The code here is made to train and evaluate the model, if you run it with a pre-trained model on the first epoch you will get the evaluation for your model. I do not have a separated code or command to do just the inference, however you can write one looking to the evaluation steps (it starts on line 246) on the speaker_id file. It basically divides the audio sample on several frames, fed it into the network and makes its decision based on the results of each frame;

2.
I do not have upload my pre-trained models, I only kept the results files, but you should get a similar result if you train your model on the same dataset;

If you want to train it on your own dataset, Mirco Ravanelli wrote some helpfull instructions for it on the SincNet repository (https://github.com/mravanelli/SincNet) if you follow it I'm sure it will work for your new dataset;

**Comment by alam-botify** [comment]
Thanks a lot for the prompt reply.
I trained a model on TIMIT dataset. I have written a script to test model on "data_lists/TIMIT_test.scp".
I run:
python inference.py --cfg=/home/ubuntu/drive_a/data_21_03/AM-MobileNet1D/cfg/AM_MobileNet1D_TIMIT.cfg
Now I am getting an error:
RuntimeError: running_mean should contain 3200 elements not 6420

The full error log is:
>python inference_new.py --cfg=/home/ubuntu/drive_a/data_21_03/AM-MobileNet1D/cfg/AM_MobileNet1D_TIMIT.cfg
Using AMSoftmax loss function...
AMSoftmax m = 0.5
LOADING MODEL.
Traceback (most recent call last):
  File "inference_new.py", line 381, in <module>
    pout[count_fr_tot - Batch_dev:count_fr_tot,:] = MOBILENET_net(inp)
  File "/home/ubuntu/tmp/AM-Mobilenet1d_venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/drive_a/data_21_03/AM-MobileNet1D/mobilenet1d.py", line 152, in forward
    x = self.normalize(x)
  File "/home/ubuntu/tmp/AM-Mobilenet1d_venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/tmp/AM-Mobilenet1d_venv/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/home/ubuntu/tmp/AM-Mobilenet1d_venv/lib/python3.6/site-packages/torch/nn/functional.py", line 1656, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 3200 elements not 6420

The link of my inference script is:
https://drive.google.com/file/d/16vw2dHzTipsObqEHiN6V2YeH1JsLkbKA/view?usp=sharing

Can you help to resolve the error?

Thanks in advance.

**Comment by joaoantoniocn** [comment]
Hi Alam, 

I saw your code and I think you made it based on the SincNet/AM-SincNet speaker_id file.
There are some minor differences between the speaker_id on the SincNet/AM-SincNet  repository and the one wrote here on the AM-MobileNet1D repository.
So, I suggest you to rewrite your script looking to the speaker_id file on the AM-MobileNet1D repository.

Let me know if you have any further issues.

**Comment by alam-botify** [comment]
yes, I wrote it based on SincNet speaker_id.
Can you tell the minor diffrences between Sincnet and AM-mobilenet1d?

As I can check there is a difference of Network Architecture (MLP, DNN1/DNN2) in sincnet.

Ok, I will check again and will rewrite the script based on AM-mobilenet1D.

**Comment by alam-botify** [comment]
I have changed the script as per AM-mobilenet1d.
Here is the link of it:
https://drive.google.com/file/d/1XFQgg2qXgWhSQjhVnpuEK7mHGwPePo-J/view?usp=sharing

I am still getting the same dimension error.
File "inference.py", line 221, in <module>
    sig_arr[count_fr, :] = signal[beg_samp:end_samp]
RuntimeError: The expanded size of the tensor (3200) must match the existing size (45068) at non-singleton dimension 1.  Target sizes: [1, 3200].  Tensor sizes: [45068]
 
Can you check my script and let me know what mistakes I am doing? 
Can you tell me the minor difference between SIncnet and AM-mobilenet1d?

Thanks in advance.

**Comment by joaoantoniocn** [comment]
The main difference between them is the shape of the tensor as you are seeing in the errors;

In your script, the first line after the while you are using:
sig_arr[count_fr, :] = signal[beg_samp:end_samp]

instead of:
sig_arr[count_fr, :] = signal[:, beg_samp:end_samp]

Also, your 'sig_arr' is first defined as a torch tensor then you redefine it as an np.array, I think you should not do that. In my implementation I set it to a np array and convert it to a tensor only in the 'inp' variable,

**Comment by alam-botify** [comment]
Thanks a lot.
finally, I can run the inference on TIMIT test_set.

I still want to know how do I test speaker recognition on a raw mono file?
How do I get predicted speaker_id / speaker_identuty for each speaker in a mono audio file?

**Comment by joaoantoniocn** [comment]
The 'pred' variable keeps the inference for each frame of the audio file. 
In the same way the 'best_class' variable storages the inference for the entire audio file, it makes it based on the prediction of each frame.

**Comment by alam-botify** [comment]
I got your point.
I got a frame-wise prediction from the model.

I still want to do prediction on the mono channel audio file(having two speakers) where I don't know who is speaking in which frame.

let's say I split my audio into frames based on vad and in each frame, only one speaker is speaking but still I don't know who is speaking in each frame (audio chunk). 
So how can I create TIMIT_test.scp (file_name_test.scp) file.

If I don't have this file, can I still do inference on mono audio file?

**Comment by alam-botify** [comment]
Hi,
I have modified the inference code to compute the d_vector of test audio chunks.

here is the link for d_vector computation:
https://drive.google.com/file/d/1VOot_amZdV7bt2ZZU0puWn9i6dkQKz-1/view?usp=sharing

Can you please check and let me know whether the above code is correct or not.

One doubt I have to ask in this.
As I can check the size of d_vector is [462] which is nothing but class_lay[-1].
So my question is how can I change this value lets say 128 or 256 or 512 of whatever dimension we want?

Thanks

**Comment by harikrishnadm** [comment]
> I got your point.
> I got a frame-wise prediction from the model.
> 
> I still want to do prediction on the mono channel audio file(having two speakers) where I don't know who is speaking in which frame.
> 
> let's say I split my audio into frames based on vad and in each frame, only one speaker is speaking but still I don't know who is speaking in each frame (audio chunk).
> So how can I create TIMIT_test.scp (file_name_test.scp) file.
> 
> If I don't have this file, can I still do inference on mono audio file?

Hi Alam,

The inference code shared in the google drive doesn't exist. Can you please share the inference.py file?
(https://drive.google.com/file/d/1XFQgg2qXgWhSQjhVnpuEK7mHGwPePo-J/view?usp=sharing)
